### ISSUE TITLE
不定期なタイミングで拡張機能(Service Worker)が無効になることがある

### ISSUE THREAD

**Issue by marokoro7636** [alpherg0221/ShortUrlExt#4]
拡張機能を更新すれば再び有効になるが，以下が必要

- [x] 当該バグが発生するタイミングの調査（どういう事をするとバグが起こるのか） 
- [x] 原因の調査
- [x] 当該バグの修正

**Comment by alpherg0221** [comment]
使用されていないときにサービスワーカーが無効になるのは仕様 ([参考](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/) ).

監視しているイベント (addListenerで登録したもの) が発生した場合にはサービスワーカーが起動するが, webRequestのイベントでは起動しない ([参考](https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension) )

**Comment by marokoro7636** [comment]
chromeが開いた状態であればService Workerは無効にならなくなった．
しかし，chromeが起動していない状態で，別アプリ上でリンクを踏んだ場合は拡張機能は動かない．この現象はほぼchromeの仕様であり，直すことが難しい．
