### ISSUE TITLE
クライアント側で追加する機能

### ISSUE THREAD

**Issue by marokoro7636** [alpherg0221/ShortUrlExt#5]
- [x] ホワイトリスト機能の追加
  - 一回許可した短縮URLに対しては確認ページを出さないようにする
- [x] ブロックルールに正規表現を使って短縮URLに絞る
  - ` https?://.{2,4}\..{2,4}/.*`
  - `https?://tinyurl.com/.*`

**Comment by alpherg0221** [comment]
ブロックルールの追加完了(3627ed1a1d6fea3b5ac48b459599edda52d19cac)

**Comment by marokoro7636** [comment]
ホワイトリスト機能の追加完了(e770055)
